apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: nirvanabrz/argocd-goserver
  newTag: ccceb3b62ad8ea66c685ddb9d4390bfd2c083838
- name: nirvanabrz/goserver
  newName: nirvanabrz/goserver
  newTag: v1
