apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

namespace: goapp

images:
 - name: nirvanabrz/goserver
   newName: nirvanabrz/goserver
   newTag: v1
   